" XDG Base Directory support
if empty($XDG_CACHE_HOME)  | let $XDG_CACHE_HOME  = $HOME."/.cache"       | endif
if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME = $HOME."/.config"      | endif
if empty($XDG_DATA_HOME)   | let $XDG_DATA_HOME   = $HOME."/.local/share" | endif
if empty($XDG_STATE_HOME)  | let $XDG_STATE_HOME  = $HOME."/.local/state" | endif

" Move viminfo to XDG location
set viminfofile=$XDG_STATE_HOME/vim/viminfo
set viminfo+=n$XDG_STATE_HOME/vim/viminfo

" Ensure the directory exists
if !isdirectory($XDG_STATE_HOME."/vim")
    call mkdir($XDG_STATE_HOME."/vim", "p", 0700)
endif

" Basic settings
set number
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent